level:  #阶段名称
  1: "|江湖好手|"
  2: "|练气|第一重|"
  3: "|练气|第二重|"
  4: "|练气|第三重|"
leveltolevel:  #升级所需,指当前需要最大修为，比如1:100表示从1级到2级需要消耗100EXP
  1: 100
  2: 200
  3: 300
  4: 400
leveltribualation: #渡劫，比如14也就是练气圆满到筑基要渡劫(测试例子),并且劫力为1(指被雷劈1下
  14: 1

levelad: #破境界通告，大境界才有，你也可以设置什么境界都有
  2:
    self: 0     #self表示是否只有自己可见
    words: "初入仙途,再接再厉"
  14:
    self: 0
    words: "成功筑基，可喜可贺"

levelquailty: #每提升等级所增加的属性
  1:   #从0升级到1时，增加的属性
    healthpoint: 0
    magicpoint: 0
  2:  #从1升级到2时，增加的属性(不是设置为，是增加
    healthpoint: 10
    magicpoint: 10
level2: #第二种修炼阶段
  1: