name: EXPengine
version: 0.0.6-SNAPSHOT
main: com.expengine.expengine.EXPengine
api-version: 1.20
author: Uiloalxise
description: 一个修仙玩法类的插件
permissions:
  exp_0.*:
    description: permissions 1
    sel:
      exp_0.expengine: ture
  exp_0.expengine:
    description: allow all player type the command
    default: true

commands:
  expengine:
    permission: exp_0
    permission-message: "你没有权限使用help命令"
    description: 帮助列出指令
    usage: /<command> [help|exp]
    aliases: expe
  expoperater:
    permission: op
    permission-message: "你没有权限使用OP命令"
    description: op权限指令
    aliases: expo
  expsystem:
    permission: exp_0
    permission-message: "你没有权限使用system命令"
    description: 系统所需指令
    aliases: exps